---

kind: Service
apiVersion: v1
metadata:
  name: beta-ubuntu-com
spec:
  selector:
    app: beta.ubuntu.com
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: beta-ubuntu-com
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: beta.ubuntu.com
    spec:
      containers:
        - name: beta-ubuntu-com
          image: prod-comms.docker-registry.canonical.com/beta.ubuntu.com:${TAG_TO_DEPLOY}
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"

---
