---

kind: Service
apiVersion: v1
metadata:
  name: cloud-init-io
spec:
  selector:
    app: cloud-init.io
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: cloud-init-io
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: cloud-init.io
    spec:
      containers:
        - name: cloud-init-io
          image: prod-comms.docker-registry.canonical.com/cloud-init.io:${TAG_TO_DEPLOY}
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            timeoutSeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            timeoutSeconds: 10
            initialDelaySeconds: 15
            periodSeconds: 15

---
