---

kind: Service
apiVersion: v1  # See https://bit.ly/2KdOtrZ
metadata:
  name: juju-is
spec:
  selector:
    app: juju.is
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---

kind: Deployment
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: juju-is
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: juju.is
    spec:
      containers:
        - name: juju-is
          image: prod-comms.docker-registry.canonical.com/juju.is:${TAG_TO_DEPLOY}
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: proxy-config
                optional: true
          env:
            - name: SENTRY_DSN
              value: https://a9c1a18b2a0a40bdae6177bb29331a2a@sentry.is.canonical.com//20
          readinessProbe:
            httpGet:
              path: /_status/check
              port: 80
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"

---
