---

kind: Service
apiVersion: v1  # See https://bit.ly/2KdOtrZ
metadata:
  name: kubeflow-news-com
spec:
  selector:
    app: kubeflow-news.com
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---

kind: Deployment
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: kubeflow-news-com
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: kubeflow-news.com
    spec:
      containers:
        - name: kubeflow-news-com
          image: prod-comms.docker-registry.canonical.com/kubeflow-news.com:${TAG_TO_DEPLOY}
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: global-envvars
                optional: true
            - configMapRef:
                name: proxy-config
                optional: true
          env:
            - name: SENTRY_DSN
              value: https://3bbe58ab41ea43329b32292ccfd09d5e@sentry.is.canonical.com//15
          readinessProbe:
            httpGet:
              path: /_status/check
              port: 80
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"

---
