---

kind: Service
apiVersion: v1
metadata:
  name: maas-io
spec:
  selector:
    app: maas.io
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: maas-io
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: maas.io
    spec:
      containers:
        - name: maas-io
          image: prod-comms.docker-registry.canonical.com/maas.io:${TAG_TO_DEPLOY}
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: envvars
                optional: true
          env:
            - name: SENTRY_DSN
              value: https://66c89fd7773e4b408d3e25867d6899e9@sentry.is.canonical.com//6
            - name: SEARCH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: google-api
                  key: google-custom-search-key
          readinessProbe:
            httpGet:
              path: /_status/check
              port: 80
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"

---
