---

kind: Service
apiVersion: v1  # See https://bit.ly/2KdOtrZ
metadata:
  name: multipass-run
spec:
  selector:
    app: multipass.run
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---

kind: Deployment
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: multipass-run
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: multipass.run
    spec:
      containers:
        - name: multipass-run
          image: prod-comms.docker-registry.canonical.com/multipass.run:${TAG_TO_DEPLOY}
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: envvars
                optional: true
          readinessProbe:
            httpGet:
              path: /_status/check
              port: 80
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"

---
