---

kind: Service
apiVersion: v1
metadata:
  name: netplan-io
spec:
  selector:
    app: netplan.io
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: netplan-io
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: netplan.io
    spec:
      containers:
        - name: netplan-io
          image: prod-comms.docker-registry.canonical.com/netplan.io:${TAG_TO_DEPLOY}
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"

---
