---

kind: Service
apiVersion: v1
metadata:
  name: old-docs-maas-io
spec:
  selector:
    app: old-docs.maas.io
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: old-docs-maas-io
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: old-docs.maas.io
    spec:
      containers:
        - name: old-docs-maas-io
          image: prod-comms.docker-registry.canonical.com/old-docs.maas.io:${TAG_TO_DEPLOY}
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: envvars
                optional: true
          readinessProbe:
            httpGet:
              path: /
              port: 80
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"

---
