---

kind: Service
apiVersion: v1
metadata:
  name: releases-demo-haus
spec:
  selector:
    app: releases.demo.haus
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: releases-demo-haus
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: releases.demo.haus
    spec:
      containers:
        - name: releases-demo-haus
          image: prod-comms.docker-registry.canonical.com/releases.demo.haus:${TAG_TO_DEPLOY}
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: envvars
                optional: true
          readinessProbe:
            httpGet:
              path: /_status/check
              port: 80
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            limits:
              memory: "128Mi"

---
