---

kind: Service
apiVersion: v1
metadata:
  name: tutorials-ubuntu-com
spec:
  selector:
    app: tutorials.ubuntu.com
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: tutorials-ubuntu-com
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: tutorials.ubuntu.com
    spec:
      containers:
        - name: tutorials-ubuntu-com
          image: prod-comms.docker-registry.canonical.com/tutorials.ubuntu.com:${TAG_TO_DEPLOY}
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            timeoutSeconds: 3
            periodSeconds: 5

---
