---

kind: Service
apiVersion: v1
metadata:
  name: ubuntu-com-blog
spec:
  selector:
    app: ubuntu.com-blog
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ubuntu-com-blog
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: ubuntu.com-blog
    spec:
      containers:
        - name: ubuntu-com-blog
          image: prod-comms.docker-registry.canonical.com/ubuntu.com:${TAG_TO_DEPLOY}
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: envvars
                optional: true
          env:
            - name: SEARCH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: google-api
                  key: google-custom-search-key
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-dsn
                  key: ubuntu-com
          readinessProbe:
            httpGet:
              path: /_status/check
              port: 80
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            limits:
              memory: "512Mi"

---
