---

kind: Service
apiVersion: v1
metadata:
  name: ubuntu-com
spec:
  selector:
    app: ubuntu.com
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ubuntu-com
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: ubuntu.com
    spec:
      containers:
        - name: ubuntu-com
          image: prod-comms.docker-registry.canonical.com/ubuntu.com:${TAG_TO_DEPLOY}
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: global-envvars
                optional: true
            - configMapRef:
                name: proxy-config
                optional: true
          env:
            - name: SEARCH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: google-api
                  key: google-custom-search-key
            - name: SENTRY_DSN
              value: https://0293bb7fc3104e56bafd2422e155790c@sentry.is.canonical.com//13
          readinessProbe:
            httpGet:
              path: /_status/check
              port: 80
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            limits:
              memory: "512Mi"

---
