---

kind: Ingress
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: {ingress_name}
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host != '{domain}' ) {
        rewrite ^ https://{domain}$request_uri? permanent;
      }
spec:
  tls:
  - secretName: {ingress_name}-tls
    hosts:
    - {domain}
    - www.{domain}
  rules:
  - host: {domain}
    http: &{service_name}_service
      paths:
      - path: /
        backend:
          serviceName: {service_name}
          servicePort: 80

  # Alias domains
  - host: www.{domain}
    http: *{service_name}_service

---
