---

kind: Ingress
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: {service_name}
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: {service_name}-tls
    hosts:
    - {domain}
  rules:
  - host: {domain}
    http:
      paths:
      - path: /
        backend:
          serviceName: {service_name}
          servicePort: 80

---
