---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: blog-ubuntu-com
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = 'design.canonical.com') {
        rewrite ^ https://blog.ubuntu.com/topics/design;
      }

      if ($host != 'blog.ubuntu.com' ) {
        rewrite ^ https://blog.ubuntu.com$request_uri? permanent;
      }
spec:
  tls:
  - secretName: blog-ubuntu-com-tls
    hosts:
    - blog.ubuntu.com
    - insights.ubuntu.com
    - design.canonical.com
  rules:
  - host: blog.ubuntu.com
    http: &blog-ubuntu-com_service
      paths:
      - path: /
        backend:
          serviceName: blog-ubuntu-com
          servicePort: 80

  # Alias domains
  - host: insights.ubuntu.com
    http: *blog-ubuntu-com_service
  - host: design.canonical.com
    http: *blog-ubuntu-com_service

---
