---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: blog-ubuntu-com
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^ https://ubuntu.com/blog$request_uri? permanent;
spec:
  tls:
  - secretName: blog-ubuntu-com-tls
    hosts:
    - blog.ubuntu.com
  - secretName: insights-ubuntu-com-tls
    hosts:
    - insights.ubuntu.com
  rules:
  - host: blog.ubuntu.com
    http: &ubuntu-com_service
      paths:
      - path: /
        backend:
          serviceName: ubuntu-com
          servicePort: 80

  # Alias domains
  - host: insights.ubuntu.com
    http: *ubuntu-com_service

---
