---

kind: Ingress
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: certification-ubuntu-com
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: certification-ubuntu-com-tls
    hosts:
    - certification.ubuntu.com
  rules:
  - host: certification.ubuntu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: certification-ubuntu-com
          servicePort: 80

---
