---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: docs-jujucharms-com
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: docs-jujucharms-com-tls
    hosts:
    - docs.jujucharms.com
  rules:
  - host: docs.jujucharms.com
    http:
      paths:
      - path: /
        backend:
          serviceName: docs-jujucharms-com
          servicePort: 80

---
