---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: docs-maas-io
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: docs-maas-io-tls
    hosts:
    - docs.maas.io
  rules:
  - host: docs.maas.io
    http:
      paths:
      - path: /
        backend:
          serviceName: docs-maas-io
          servicePort: 80

---
