---

kind: Ingress
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: dqlite-io
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host != 'dqlite.io' ) {
        rewrite ^ https://dqlite.io$request_uri? permanent;
      }
      more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
spec:
  tls:
  - secretName: dqlite-io-tls
    hosts:
    - dqlite.io
    - www.dqlite.io
  rules:
  - host: dqlite.io
    http: &dqlite-io_service
      paths:
      - path: /
        backend:
          serviceName: dqlite-io
          servicePort: 80

  # Alias domains
  - host: www.dqlite.io
    http: *dqlite-io_service

---
