---

kind: Ingress
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: engage-canonical-com
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
spec:
  tls:
  - secretName: engage-canonical-com-tls
    hosts:
    - engage.canonical.com
  rules:
  - host: engage.canonical.com
    http:
      paths:
      - path: /
        backend:
          serviceName: engage-canonical-com
          servicePort: 80

---
