---

kind: Ingress
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: jaas-ai
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = 'docs.jujucharms.com' ) {
        rewrite ^ https://jaas.ai/docs$request_uri? permanent;
      }
      if ($host != 'jaas.ai' ) {
        rewrite ^ https://jaas.ai$request_uri? permanent;
      }
      more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
spec:
  tls:
  - secretName: jaas-ai-tls
    hosts:
    - jaas.ai
    - www.jaas.ai
  - secretName: docs-jujucharms-com-tls
    hosts:
    - docs.jujucharms.com
  rules:
  - host: jaas.ai
    http: &jaas-ai_service
      paths:
      - path: /
        backend:
          serviceName: jaas-ai
          servicePort: 80

  # Alias domains
  - host: www.jaas.ai
    http: *jaas-ai_service
  - host: docs.jujucharms.com
    http: *jaas-ai_service

---
