---

kind: Ingress
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: jaas-ai
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host != 'jaas.ai' ) {
        rewrite ^ https://jaas.ai$request_uri? permanent;
      }
spec:
  tls:
  - secretName: jaas-ai-tls
    hosts:
    - jaas.ai
    - www.jaas.ai
  rules:
  - host: jaas.ai
    http: &jaas-ai_service
      paths:
      - path: /
        backend:
          serviceName: jaas-ai
          servicePort: 80

  # Alias domains
  - host: www.jaas.ai
    http: *jaas-ai_service

---
