---

kind: Ingress
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: kubeflow-news-com
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host != 'kubeflow-news.com' ) {
        rewrite ^ https://kubeflow-news.com$request_uri? permanent;
      }
spec:
  tls:
  - secretName: kubeflow-news-com-tls
    hosts:
    - kubeflow-news.com
    - www.kubeflow-news.com
  rules:
  - host: kubeflow-news.com
    http: &kubeflow-news-com_service
      paths:
      - path: /
        backend:
          serviceName: kubeflow-news-com
          servicePort: 80

  # Alias domains
  - host: www.kubeflow-news.com
    http: *kubeflow-news-com_service

---
