---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: microk8s-io
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: microk8s-io-tls
    hosts:
    - microk8s.io
  rules:
  - host: microk8s.io
    http:
      paths:
      - path: /
        backend:
          serviceName: microk8s-io
          servicePort: 80

---
