---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: mir-server-io
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: mir-server-io-tls
    hosts:
    - mir-server.io
  rules:
  - host: mir-server.io
    http:
      paths:
      - path: /
        backend:
          serviceName: mir-server-io
          servicePort: 80

---
