---

kind: Ingress
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: multipass-run
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host != 'multipass.run' ) {
        rewrite ^ https://multipass.run$request_uri? permanent;
      }
spec:
  tls:
  - secretName: multipass-run-tls
    hosts:
    - multipass.run
    - www.multipass.run
  rules:
  - host: multipass.run
    http: &multipass-run_service
      paths:
      - path: /
        backend:
          serviceName: multipass-run
          servicePort: 80

  # Alias domains
  - host: www.multipass.run
    http: *multipass-run_service

---
