---

kind: Ingress
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: old-docs-jujucharms-com
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
spec:
  tls:
  - secretName: old-docs-jujucharms-com-tls
    hosts:
    - old-docs.jujucharms.com
  rules:
  - host: old-docs.jujucharms.com
    http:
      paths:
      - path: /
        backend:
          serviceName: old-docs-jujucharms-com
          servicePort: 80

---
