---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: snapcraft-io
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = 'docs.snapcraft.io' ) {
        rewrite ^ https://snapcraft.io/docs$request_uri? permanent;
      }
      if ($host != 'snapcraft.io' ) {
        rewrite ^ https://snapcraft.io$request_uri? permanent;
      }
spec:
  tls:
  - secretName: snapcraft-io-tls
    hosts:
    - snapcraft.io
    - www.snapcraft.io
  - secretName: docs-snapcraft-io-tls
    hosts:
    - docs.snapcraft.io
  rules:
  - host: snapcraft.io
    http: &snapcraft-io_service
      paths:
      - path: /
        backend:
          serviceName: snapcraft-io
          servicePort: 80
  - host: www.snapcraft.io
    http: *snapcraft-io_service
  - host: docs.snapcraft.io
    http: *snapcraft-io_service

---
