---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: threesixty-canonical-com
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host != '360.canonical.com' ) {
        rewrite ^ https://360.canonical.com$request_uri? permanent;
      }
spec:
  tls:
  - secretName: threesixty-canonical-com-tls
    hosts:
    - 360.canonical.com
  rules:
  - host: 360.canonical.com
    http: &threesixty-canonical-com_service
      paths:
      - path: /
        backend:
          serviceName: threesixty-canonical-com
          servicePort: 80

  # Alias domains
  - host: www.360.canonical.com
    http: *threesixty-canonical-com_service

---
