---

kind: Ingress
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: ubuntu-com
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host != 'ubuntu.com' ) {
        rewrite ^ https://ubuntu.com$request_uri? permanent;
      }
      more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect, <https://www.google-analytics.com>; rel=preconnect, <https://www.gstatic.com>; rel=preconnect, <https://res.cloudinary.com>; rel=preconnect";

spec:
  rules:
  - host: ubuntu.com
    http: &ubuntu-com_service
      paths:
      - path: /blog
        backend:
          serviceName: ubuntu-com-blog
          servicePort: 80
      - path: /
        backend:
          serviceName: ubuntu-com
          servicePort: 80

  # Alias domains
  - host: www.ubuntu.com
    http: *ubuntu-com_service
  - host: ubuntu.net
    http: *ubuntu-com_service
  - host: www.ubuntu.net
    http: *ubuntu-com_service
  - host: ubunut.com
    http: *ubuntu-com_service
  - host: www.ubunut.com
    http: *ubuntu-com_service
  - host: ubuntulinux.org
    http: *ubuntu-com_service
  - host: www.ubuntulinux.org
    http: *ubuntu-com_service

---
