---

kind: Ingress
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: ubuntu-com-internal
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = 'www.ubuntu.com' ) {
        rewrite ^ https://ubuntu.com$request_uri? permanent;
      }

spec:
  rules:
  - host: ubuntu-com.internal
    http:
      paths:
      - path: /
        backend:
          serviceName: ubuntu-com
          servicePort: 80

---
