---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: usn-ubuntu-com
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
spec:
  tls:
  - secretName: usn-ubuntu-com-tls
    hosts:
    - usn.ubuntu.com
  rules:
  - host: usn.ubuntu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: usn-ubuntu-com
          servicePort: 80

---
