---

kind: Ingress
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: webteam-ircbot-canonical-com
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: webteam-ircbot-canonical-com-tls
    hosts:
    - webteam-ircbot.canonical.com
  rules:
  - host: webteam-ircbot.canonical.com
    http:
      paths:
      - path: /
        backend:
          serviceName: webteam-ircbot-canonical-com
          servicePort: 80

---
