---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: beta-staging-ubuntu-com
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
      rewrite ^ http://mongoose.staging.ubuntu.com$request_uri? redirect;
spec:
  tls:
  - secretName: beta-staging-ubuntu-com-tls
    hosts:
    - beta.staging.ubuntu.com
  rules:
  - host: beta.staging.ubuntu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: beta-ubuntu-com
          servicePort: 80

---
