---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: blog-staging-ubuntu-com
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
      rewrite ^ https://staging.ubuntu.com/blog$request_uri? permanent;
spec:
  tls:
  - secretName: blog-staging-ubuntu-com-tls
    hosts:
    - blog.staging.ubuntu.com
  - secretName: insights-staging-ubuntu-com-tls
    hosts:
    - insights.staging.ubuntu.com
  rules:
  - host: blog.staging.ubuntu.com
    http: &ubuntu-com_service
      paths:
      - path: /
        backend:
          serviceName: ubuntu-com
          servicePort: 80

  # Alias domains
  - host: insights.staging.ubuntu.com
    http: *ubuntu-com_service

---
