---

kind: Ingress
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: certification-staging-ubuntu-com
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
spec:
  tls:
  - secretName: certification-staging-ubuntu-com-tls
    hosts:
    - certification.staging.ubuntu.com
  rules:
  - host: certification.staging.ubuntu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: certification-ubuntu-com
          servicePort: 80

---
