---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: docs-staging-maas-io
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
spec:
  tls:
  - secretName: docs-staging-maas-io-tls
    hosts:
    - docs.staging.maas.io
  rules:
  - host: docs.staging.maas.io
    http:
      paths:
      - path: /
        backend:
          serviceName: docs-maas-io
          servicePort: 80

---
