---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: docs-staging-vanillaframework-io
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
      more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
spec:
  tls:
  - secretName: docs-staging-vanillaframework-io-tls
    hosts:
    - docs.staging.vanillaframework.io
  rules:
  - host: docs.staging.vanillaframework.io
    http:
      paths:
      - path: /
        backend:
          serviceName: docs-vanillaframework-io
          servicePort: 80

---
