---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: docs-staging-jujucharms-com
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
spec:
  tls:
  - secretName: docs-staging-jujucharms-com-tls
    hosts:
    - docs.staging.jujucharms.com
  rules:
  - host: docs.staging.jujucharms.com
    http:
      paths:
      - path: /
        backend:
          serviceName: docs-jujucharms-com
          servicePort: 80

---
