---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: insights-staging-ubuntu-com
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
      rewrite ^ https://blog.staging.ubuntu.com$request_uri? permanent;
spec:
  tls:
  - secretName: insights-staging-ubuntu-com-tls
    hosts:
    - insights.staging.ubuntu.com
  rules:
  - host: insights.staging.ubuntu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: blog-ubuntu-com
          servicePort: 80

---
