---

kind: Ingress
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: releases-demo-haus
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
spec:
  rules:
  - host: releases.demo.haus
    http:
      paths:
      - path: /
        backend:
          serviceName: releases-demo-haus
          servicePort: 80

---
