---

kind: Ingress
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: staging-jaas-ai
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
      if ($host = 'docs.staging.jujucharms.com' ) {
        rewrite ^ https://staging.jaas.ai/docs$request_uri? permanent;
      }
spec:
  tls:
  - secretName: staging-jaas-ai-tls
    hosts:
    - staging.jaas.ai
  - secretName: docs-staging-jujucharms-com-tls
    hosts:
    - docs.staging.jujucharms.com
  rules:
  - host: staging.jaas.ai
    http: &jaas-ai_service
      paths:
      - path: /
        backend:
          serviceName: jaas-ai
          servicePort: 80
  - host: docs.staging.jujucharms.com
    http: *jaas-ai_service

---
