---

kind: Ingress
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: staging-ubuntu-com
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host != 'staging.ubuntu.com' ) {
        rewrite ^ https://staging.ubuntu.com$request_uri? permanent;
      }
      more_set_headers "X-Robots-Tag: noindex";
      more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect, <https://res.cloudinary.com>; rel=preconnect";
spec:
  tls:
  - secretName: staging-ubuntu-com-tls
    hosts:
    - staging.ubuntu.com
  rules:
  - host: staging.ubuntu.com
    http: &ubuntu-com_service
      paths:
      - path: /blog
        backend:
          serviceName: ubuntu-com-blog
          servicePort: 80
      - path: /
        backend:
          serviceName: ubuntu-com
          servicePort: 80

  # Alias domains
  - host: www.staging.ubuntu.com
    http: *ubuntu-com_service

---
