---

kind: Ingress
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: staging-jaas-ai
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
spec:
  tls:
  - secretName: staging-jaas-ai-tls
    hosts:
    - staging.jaas.ai
  rules:
  - host: staging.jaas.ai
    http:
      paths:
      - path: /
        backend:
          serviceName: jaas-ai
          servicePort: 80

---
