---

kind: Ingress
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: staging-dqlite-io
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
spec:
  tls:
  - secretName: staging-dqlite-io-tls
    hosts:
    - staging.dqlite.io
  rules:
  - host: staging.dqlite.io
    http:
      paths:
      - path: /
        backend:
          serviceName: dqlite-io
          servicePort: 80

---
