---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: staging-vanillaframework-io
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
      more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
spec:
  tls:
  - secretName: staging-vanillaframework-io-tls
    hosts:
    - staging.vanillaframework.io
  rules:
  - host: staging.vanillaframework.io
    http:
      paths:
      - path: /
        backend:
          serviceName: vanillaframework-io
          servicePort: 80

---
