---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: staging-snapcraft-io
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = 'docs.staging.snapcraft.io' ) {
        rewrite ^ https://staging.snapcraft.io/docs$request_uri? permanent;
      }
      more_set_headers "X-Robots-Tag: noindex";
spec:
  tls:
  - secretName: staging-snapcraft-io-tls
    hosts:
    - staging.snapcraft.io
  - secretName: docs-staging-snapcraft-io-tls
    hosts:
    - docs-staging.snapcraft.io
  rules:
  - host: staging.snapcraft.io
    http: &snapcraft-io_service
      paths:
      - path: /
        backend:
          serviceName: snapcraft-io
          servicePort: 80
  # Alias domains
  - host: docs.staging.snapcraft.io
    http: *snapcraft-io_service

---
