---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: staging-ubuntu-com
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
      if ($host = 'www.staging.ubuntu.com' ) {
        rewrite ^ https://staging.ubuntu.com$request_uri? permanent;
      }
spec:
  tls:
  - secretName: staging-ubuntu-com-tls
    hosts:
    - staging.ubuntu.com
  rules:
  - host: staging.ubuntu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ubuntu-com
          servicePort: 80
  - host: www.staging.ubuntu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ubuntu-com
          servicePort: 80

---
