---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: tutorials-staging-ubuntu-com
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
spec:
  tls:
  - secretName: tutorials-staging-ubuntu-com-tls
    hosts:
    - tutorials.staging.ubuntu.com
  rules:
  - host: tutorials.staging.ubuntu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: tutorials-ubuntu-com
          servicePort: 80

---
