---

kind: Ingress
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: webteam-kpi-webhook-staging-canonical-com
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
spec:
  tls:
  - secretName: webteam-kpi-webhook-staging-canonical-com-tls
    hosts:
    - webteam-kpi-webhook.staging.canonical.com
  rules:
  - host: webteam-kpi-webhook.staging.canonical.com
    http:
      paths:
      - path: /
        backend:
          serviceName: webteam-kpi-webhook-canonical-com
          servicePort: 80

---
